// Metadata generated by weweb-metadata on 2026-03-14T19:28:01.971Z
window.METADATA = {
  "1": {
    "title": "Grandmas Home",
    "content": "This is the home for a grandma",
    "image_url": "https://images.pexels.com/photos/34123173/pexels-photo-34123173.jpeg"
  },
  "2": {
    "title": "Suite",
    "content": "A fine home for anyone",
    "image_url": "https://images.pexels.com/photos/105933/pexels-photo-105933.jpeg"
  }
};